import Link from 'next/link';

export const metadata = {
  title: 'Terms & Conditions – Wide Wings Media',
  description: 'Terms and Conditions for Wide Wings Media, LLC. Read our terms of service, payment policy, refund policy, and legal agreements.',
};

const sections = [
  {
    id: 'general',
    title: 'General Terms',
    content: `By accessing and placing an order with Wide Wings Media, LLC, you confirm that you are in agreement with and bound by the terms of service contained in the Terms & Conditions outlined below. These terms apply to the entire website and any email or other type of communication between you and Wide Wings Media, LLC.

Under no circumstances shall Wide Wings Media, LLC team be liable for any direct, indirect, special, incidental or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site, even if Wide Wings Media, LLC team or an authorized representative has been advised of the possibility of such damages. If your use of materials from this site results in the need for servicing, repair or correction of equipment or data, you assume any costs thereof.

Wide Wings Media, LLC will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the rights to change prices and revise the resources usage policy at any moment.`,
  },
  {
    id: 'license',
    title: 'License',
    content: `Wide Wings Media, LLC grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the website strictly in accordance with the terms of this Agreement.

These Terms & Conditions are a contract between you and Wide Wings Media, LLC (referred to in these Terms & Conditions as "Wide Wings Media, LLC", "us", "we" or "our"), the provider of the Wide Wings Media, LLC website and the services accessible from the Wide Wings Media, LLC website (which are collectively referred to in these Terms & Conditions as the "Wide Wings Media, LLC Service").

You are agreeing to be bound by these Terms & Conditions. If you do not agree to these Terms & Conditions, please do not use the Wide Wings Media, LLC Service. In these Terms & Conditions, "you" refers both to you as an individual and to the entity you represent. If you violate any of these Terms & Conditions, we reserve the right to cancel your account or block access to your account without notice.`,
  },
  {
    id: 'definitions',
    title: 'Definitions and Key Terms',
    content: `To help explain things as clearly as possible in these Terms & Conditions, every time any of these terms are referenced, they are strictly defined as:

Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.

Company: when these terms mention "Company," "we," "us," or "our," it refers to Wide Wings Media, LLC, (Dubai, Al Quoz Industrial Area 3, Goshi Warehouse City, Warehouse #47) that is responsible for your information under these Terms & Conditions.

Country: where Wide Wings Media, LLC or the owners/founders of Wide Wings Media, LLC are based, in this case is United Arab Emirates.

Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Wide Wings Media, LLC and use the services.

Service: refers to the service provided by Wide Wings Media, LLC as described in the relative terms (if available) and on this platform.

Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.

Website: Wide Wings Media, LLC's site, which can be accessed via this URL: https://wide-wings.ae/

You: a person or entity that is registered with Wide Wings Media, LLC to use the Services.`,
  },
  {
    id: 'restrictions',
    title: 'Restrictions',
    content: `You agree not to, and you will not permit others to:

• License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the website or make the platform available to any third party.

• Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the website.

• Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of Wide Wings Media, LLC or its affiliates, partners, suppliers or the licensors of the website.`,
  },
  {
    id: 'payment',
    title: 'Payment',
    content: `You agree to pay all fees or charges to your account for the Services in accordance with the fees, charges, and billing terms in effect at the time that each fee or charge is due and payable. Where Services are offered on a free trial basis, payment may be required after the free trial period ends, and not before.

If auto-renewal is enabled for the Services you have subscribed for, you will be charged automatically in accordance with the term you selected. We require you to provide us with a valid credit card or other payment account information ("Payment Account") as a condition to signing up for the Premium Service. Your Payment Account information will be kept current, complete, and accurate, and you will notify us of any changes to your Payment Account.

No contract will exist between you and Wide Wings Media, LLC for the Services until Wide Wings Media, LLC accepts your order by a confirmatory e-mail, SMS/MMS message, or other appropriate means of communication. You are responsible for any third-party fees that you may incur when using the Services.`,
  },
  {
    id: 'refund',
    title: 'Return and Refund Policy',
    content: `Thanks for shopping at Wide Wings Media, LLC. We appreciate the fact that you like to buy the stuff we build. We also want to make sure you have a rewarding experience while you're exploring, evaluating, and purchasing our products.

As with any shopping experience, there are terms and conditions that apply to transactions at Wide Wings Media, LLC. We'll be as brief as our attorneys will allow. The main thing to remember is that by placing an order or making a purchase at Wide Wings Media, LLC, you agree to the terms set forth below along with Wide Wings Media, LLC's Privacy Policy.

If, for any reason, you are not completely satisfied with any good or service that we provide, don't hesitate to contact us and we will discuss any of the issues you are going through with our product.`,
  },
  {
    id: 'suggestions',
    title: 'Your Suggestions',
    content: `Any feedback, comments, ideas, improvements or suggestions (collectively, "Suggestions") provided by you to Wide Wings Media, LLC with respect to the website shall remain the sole and exclusive property of Wide Wings Media, LLC.

Wide Wings Media, LLC shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without any credit or any compensation to you.`,
  },
  {
    id: 'consent',
    title: 'Your Consent',
    content: `We've updated our Terms & Conditions to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our website, registering an account, or making a purchase, you hereby consent to our Terms & Conditions.`,
  },
  {
    id: 'links',
    title: 'Links to Other Websites',
    content: `These Terms & Conditions apply only to the Services. The Services may contain links to other websites not operated or controlled by Wide Wings Media, LLC. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us.

Please remember that when you use a link to go from the Services to another website, our Terms & Conditions are no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website's own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.`,
  },
  {
    id: 'cookies',
    title: 'Cookies',
    content: `Wide Wings Media, LLC uses "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our website but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website as we would not be able to remember that you had logged in previously.

Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.`,
  },
  {
    id: 'changes',
    title: 'Changes to Our Terms & Conditions',
    content: `You acknowledge and agree that Wide Wings Media, LLC may stop (permanently or temporarily) providing the Service (or any features within the Service) to you or to users generally at Wide Wings Media, LLC's sole discretion, without prior notice to you. You may stop using the Service at any time. You do not need to specifically inform Wide Wings Media, LLC when you stop using the Service.

You acknowledge and agree that if Wide Wings Media, LLC disables access to your account, you may be prevented from accessing the Service, your account details or any files or other materials which is contained in your account.

If we decide to change our Terms & Conditions, we will post those changes on this page, and/or update the Terms & Conditions modification date below.`,
  },
  {
    id: 'modifications',
    title: 'Modifications to Our Website',
    content: `Wide Wings Media, LLC reserves the right to modify, suspend or discontinue, temporarily or permanently, the website or any service to which it connects, with or without notice and without liability to you.`,
  },
  {
    id: 'updates',
    title: 'Updates to Our Website',
    content: `Wide Wings Media, LLC may from time to time provide enhancements or improvements to the features/functionality of the website, which may include patches, bug fixes, updates, upgrades and other modifications ("Updates").

Updates may modify or delete certain features and/or functionalities of the website. You agree that Wide Wings Media, LLC has no obligation to (i) provide any Updates, or (ii) continue to provide or enable any particular features and/or functionalities of the website to you.

You further agree that all Updates will be (i) deemed to constitute an integral part of the website, and (ii) subject to the terms and conditions of this Agreement.`,
  },
  {
    id: 'third-party',
    title: 'Third-Party Services',
    content: `We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services ("Third-Party Services").

You acknowledge and agree that Wide Wings Media, LLC shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. Wide Wings Media, LLC does not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.

Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions.`,
  },
  {
    id: 'termination',
    title: 'Term and Termination',
    content: `This Agreement shall remain in effect until terminated by you or Wide Wings Media, LLC. Wide Wings Media, LLC may, in its sole discretion, at any time and for any or no reason, suspend or terminate this Agreement with or without prior notice.

This Agreement will terminate immediately, without prior notice from Wide Wings Media, LLC, in the event that you fail to comply with any provision of this Agreement. You may also terminate this Agreement by deleting the website and all copies thereof from your computer.

Upon termination of this Agreement, you shall cease all use of the website and delete all copies of the website from your computer.

Termination of this Agreement will not limit any of Wide Wings Media, LLC's rights or remedies at law or in equity in case of breach by you (during the term of this Agreement) of any of your obligations under the present Agreement.`,
  },
  {
    id: 'copyright',
    title: 'Copyright Infringement Notice',
    content: `If you are a copyright owner or such owner's agent and believe any material on our website constitutes an infringement on your copyright, please contact us setting forth the following information: (a) a physical or electronic signature of the copyright owner or a person authorized to act on his behalf; (b) identification of the material that is claimed to be infringing; (c) your contact information, including your address, telephone number, and an email; (d) a statement by you that you have a good faith belief that use of the material is not authorized by the copyright owners; and (e) the a statement that the information in the notification is accurate, and, under penalty of perjury you are authorized to act on behalf of the owner.`,
  },
  {
    id: 'indemnification',
    title: 'Indemnification',
    content: `You agree to indemnify and hold Wide Wings Media, LLC and its parents, subsidiaries, affiliates, officers, employees, agents, partners and licensors (if any) harmless from any claim or demand, including reasonable attorneys' fees, due to or arising out of your: (a) use of the website; (b) violation of this Agreement or any law or regulation; or (c) violation of any right of a third party.`,
  },
  {
    id: 'no-warranties',
    title: 'No Warranties',
    content: `The website is provided to you "AS IS" and "AS AVAILABLE" and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, Wide Wings Media, LLC, on its own behalf and on behalf of its affiliates and its and their respective licensors and service providers, expressly disclaims all warranties, whether express, implied, statutory or otherwise, with respect to the website, including all implied warranties of merchantability, fitness for a particular purpose, title and non-infringement, and warranties that may arise out of course of dealing, course of performance, usage or trade practice.

Without limitation to the foregoing, Wide Wings Media, LLC provides no warranty or undertaking, and makes no representation of any kind that the website will meet your requirements, achieve any intended results, be compatible or work with any other software, systems or services, operate without interruption, meet any performance or reliability standards or be error free or that any errors or defects can or will be corrected.`,
  },
  {
    id: 'limitation',
    title: 'Limitation of Liability',
    content: `Notwithstanding any damages that you might incur, the entire liability of Wide Wings Media, LLC and any of its suppliers under any provision of this Agreement and your exclusive remedy for all of the foregoing shall be limited to the amount actually paid by you for the website.

To the maximum extent permitted by applicable law, in no event shall Wide Wings Media, LLC or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to, damages for loss of profits, loss of data or other information, for business interruption, for personal injury, loss of privacy arising out of or in any way related to the use of or inability to use the website, third-party software and/or third-party hardware used with the website, or otherwise in connection with any provision of this Agreement), even if Wide Wings Media, LLC or any supplier has been advised of the possibility of such damages and even if the remedy fails of its essential purpose.`,
  },
  {
    id: 'severability',
    title: 'Severability',
    content: `If any provision of this Agreement is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect.

This Agreement, together with the Privacy Policy and any other legal notices published by Wide Wings Media, LLC on the Services, shall constitute the entire agreement between you and Wide Wings Media, LLC concerning the Services. If any provision of this Agreement is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of this Agreement, which shall remain in full force and effect.

YOU AND Wide Wings Media, LLC AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE SERVICES MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.`,
  },
  {
    id: 'waiver',
    title: 'Waiver',
    content: `Except as provided herein, the failure to exercise a right or to require performance of an obligation under this Agreement shall not effect a party's ability to exercise such right or require such performance at any time thereafter nor shall be the waiver of a breach constitute waiver of any subsequent breach.

No failure to exercise, and no delay in exercising, on the part of either party, any right or any power under this Agreement shall operate as a waiver of that right or power. Nor shall any single or partial exercise of any right or power under this Agreement preclude further exercise of that or any other right granted herein. In the event of a conflict between this Agreement and any applicable purchase or other terms, the terms of this Agreement shall govern.`,
  },
  {
    id: 'amendments',
    title: 'Amendments to this Agreement',
    content: `Wide Wings Media, LLC reserves the right, at its sole discretion, to modify or replace this Agreement at any time. If a revision is material we will provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.

By continuing to access or use our website after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use Wide Wings Media, LLC.`,
  },
  {
    id: 'entire-agreement',
    title: 'Entire Agreement',
    content: `The Agreement constitutes the entire agreement between you and Wide Wings Media, LLC regarding your use of the website and supersedes all prior and contemporaneous written or oral agreements between you and Wide Wings Media, LLC.

You may be subject to additional terms and conditions that apply when you use or purchase other Wide Wings Media, LLC's services, which Wide Wings Media, LLC will provide to you at the time of such use or purchase.`,
  },
  {
    id: 'updates-terms',
    title: 'Updates to Our Terms',
    content: `We may change our Service and policies, and we may need to make changes to these Terms so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to these Terms and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Terms. If you do not want to agree to these or any updated Terms, you can delete your account.`,
  },
  {
    id: 'intellectual-property',
    title: 'Intellectual Property',
    content: `The website and its entire contents, features and functionality (including but not limited to all information, software, text, displays, images, video and audio, and the design, selection and arrangement thereof), are owned by Wide Wings Media, LLC, its licensors or other providers of such material and are protected by United Arab Emirates and international copyright, trademark, patent, trade secret and other intellectual property or proprietary rights laws.

The material may not be copied, modified, reproduced, downloaded or distributed in any way, in whole or in part, without the express prior written permission of Wide Wings Media, LLC, unless and except as is expressly provided in these Terms & Conditions. Any unauthorized use of the material is prohibited.`,
  },
  {
    id: 'arbitration',
    title: 'Agreement to Arbitrate',
    content: `This section applies to any dispute EXCEPT IT DOESN'T INCLUDE A DISPUTE RELATING TO CLAIMS FOR INJUNCTIVE OR EQUITABLE RELIEF REGARDING THE ENFORCEMENT OR VALIDITY OF YOUR OR Wide Wings Media, LLC'S INTELLECTUAL PROPERTY RIGHTS. The term "dispute" means any dispute, action, or other controversy between you and Wide Wings Media, LLC concerning the Services or this agreement, whether in contract, warranty, tort, statute, regulation, ordinance, or any other legal or equitable basis. "Dispute" will be given the broadest possible meaning allowable under law.`,
  },
  {
    id: 'notice-dispute',
    title: 'Notice of Dispute',
    content: `In the event of a dispute, you or Wide Wings Media, LLC must give the other a Notice of Dispute, which is a written statement that sets forth the name, address, and contact information of the party giving it, the facts giving rise to the dispute, and the relief requested. You must send any Notice of Dispute via email to: info@wide-wings.ae. Wide Wings Media, LLC will send any Notice of Dispute to you by mail to your address if we have it, or otherwise to your email address. You and Wide Wings Media, LLC will attempt to resolve any dispute through informal negotiation within sixty (60) days from the date the Notice of Dispute is sent. After sixty (60) days, you or Wide Wings Media, LLC may commence arbitration.`,
  },
  {
    id: 'binding-arbitration',
    title: 'Binding Arbitration',
    content: `If you and Wide Wings Media, LLC don't resolve any dispute by informal negotiation, any other effort to resolve the dispute will be conducted exclusively by binding arbitration as described in this section. You are giving up the right to litigate (or participate in as a party or class member) all disputes in court before a judge or jury. The dispute shall be settled by binding arbitration in accordance with the commercial arbitration rules of the American Arbitration Association. Either party may seek any interim or preliminary injunctive relief from any court of competent jurisdiction, as necessary to protect the party's rights or property pending the completion of arbitration. Any and all legal, accounting, and other costs, fees, and expenses incurred by the prevailing party shall be borne by the non-prevailing party.`,
  },
  {
    id: 'submissions',
    title: 'Submissions and Privacy',
    content: `In the event that you submit or post any ideas, creative suggestions, designs, photographs, information, advertisements, data or proposals, including ideas for new or improved products, services, features, technologies or promotions, you expressly agree that such submissions will automatically be treated as non-confidential and non-proprietary and will become the sole property of Wide Wings Media, LLC without any compensation or credit to you whatsoever. Wide Wings Media, LLC and its affiliates shall have no obligations with respect to such submissions or posts and may use the ideas contained in such submissions or posts for any purposes in any medium in perpetuity, including, but not limited to, developing, manufacturing, and marketing products and services using such ideas.`,
  },
  {
    id: 'promotions',
    title: 'Promotions',
    content: `Wide Wings Media, LLC may, from time to time, include contests, promotions, sweepstakes, or other activities ("Promotions") that require you to submit material or information concerning yourself. Please note that all Promotions may be governed by separate rules that may contain certain eligibility requirements, such as restrictions as to age and geographic location. You are responsible to read all Promotions rules to determine whether or not you are eligible to participate. If you enter any Promotion, you agree to abide by and to comply with all Promotions Rules.`,
  },
  {
    id: 'typographical',
    title: 'Typographical Errors',
    content: `In the event a product and/or service is listed at an incorrect price or with incorrect information due to typographical error, we shall have the right to refuse or cancel any orders placed for the product and/or service listed at the incorrect price. We shall have the right to refuse or cancel any such orders whether or not the order has been confirmed and your credit card charged. If your credit card has already been charged for the purchase and your order is cancelled, we shall immediately issue a credit to your credit card account or other payment account in the amount of the charge.`,
  },
  {
    id: 'miscellaneous',
    title: 'Miscellaneous',
    content: `If for any reason a court of competent jurisdiction finds any provision or portion of these Terms & Conditions to be unenforceable, the remainder of these Terms & Conditions will continue in full force and effect. Any waiver of any provision of these Terms & Conditions will be effective only if in writing and signed by an authorized representative of Wide Wings Media, LLC. Wide Wings Media, LLC will be entitled to injunctive or other equitable relief (without the obligations of posting any bond or surety) in the event of any breach or anticipatory breach by you. Wide Wings Media, LLC operates and controls the Wide Wings Media, LLC Service from its offices in United Arab Emirates. The Service is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation. Accordingly, those persons who choose to access the Wide Wings Media, LLC Service from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable. These Terms & Conditions (which include and incorporate the Wide Wings Media, LLC Privacy Policy) contains the entire understanding, and supersedes all prior understandings, between you and Wide Wings Media, LLC concerning its subject matter, and cannot be changed or modified by you. The section headings used in this Agreement are for convenience only and will not be given any legal import.`,
  },
  {
    id: 'disclaimer',
    title: 'Disclaimer',
    content: `Wide Wings Media, LLC is not responsible for any content, code or any other imprecision.

Wide Wings Media, LLC does not provide warranties or guarantees.

In no event shall Wide Wings Media, LLC be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. The Company reserves the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice.

The Wide Wings Media, LLC Service and its contents are provided "as is" and "as available" without any warranty or representations of any kind, whether express or implied. Wide Wings Media, LLC is a distributor (without any obligation to verify) and not a publisher of these third-party supplier and service. As such, Wide Wings Media, LLC has no editorial control over such content. Any opinions, advice, statements, services, offers, or other information or content expressed or made available by third parties, including information providers, are those of the respective authors or distributors and not Wide Wings Media, LLC. Wide Wings Media, LLC does not guarantee the accuracy, completeness, usefulness or adequacy of any resource, information, apparatus, product, or process available at or through the website, and Wide Wings Media, LLC shall not be liable for any loss or damage that may result from your reliance on any such resource, information, apparatus, product, or process. It is your responsibility to evaluate the accuracy, completeness or usefulness of any opinion, advice, or other content available through the website.`,
  },
];

export default function TermsConditionsPage() {
  return (
    <main style={{ paddingBottom: '80px', background: '#fff' }}>
      {/* Hero */}
      <section style={{ position: 'relative', background: '#0d0d20', padding: '140px 0 80px', overflow: 'hidden' }}>
        <div aria-hidden="true" style={{ position: 'absolute', inset: 0, background: 'radial-gradient(ellipse 60% 60% at 30% 50%, rgba(167,49,132,0.18) 0%, transparent 70%)', pointerEvents: 'none' }} />
        <div className="container" style={{ position: 'relative', zIndex: 1 }}>
          <nav style={{ display: 'flex', alignItems: 'center', gap: 8, fontFamily: 'Calibri, sans-serif', fontSize: '0.88rem', color: 'rgba(255,255,255,0.45)', marginBottom: 20 }} aria-label="breadcrumb">
            <Link href="/" style={{ color: 'rgba(255,255,255,0.45)', textDecoration: 'none' }}>Home</Link>
            <span style={{ color: 'rgba(255,255,255,0.25)' }}>/</span>
            <span>Terms &amp; Conditions</span>
          </nav>
          <p style={{ fontFamily: 'Nexa, sans-serif', fontSize: '0.78rem', fontWeight: 800, letterSpacing: '0.14em', textTransform: 'uppercase', color: '#a73184', margin: '0 0 12px' }}>Legal</p>
          <h1 style={{ fontFamily: 'Nexa, sans-serif', fontSize: 'clamp(2.4rem, 5vw, 4rem)', fontWeight: 800, color: '#fff', margin: '0 0 20px', lineHeight: 1.12 }}>
            Terms &amp; Conditions
          </h1>
          <p style={{ fontFamily: 'Calibri, sans-serif', fontSize: 'clamp(1rem, 1.8vw, 1.12rem)', color: 'rgba(255,255,255,0.6)', maxWidth: 620, lineHeight: 1.75, margin: 0 }}>
            Last updated: January 1, 2026. Please read these Terms &amp; Conditions carefully before using the Wide Wings Media website.
          </p>
        </div>
      </section>

      {/* Content */}
      <div className="container" style={{ maxWidth: 900, paddingTop: 60 }}>
        {/* Table of contents */}
        <nav style={{ background: '#f8f8fc', border: '1px solid rgba(0,0,0,.07)', padding: '28px 32px', marginBottom: 56 }}>
          <p style={{ fontWeight: 700, fontSize: '0.85rem', letterSpacing: '0.1em', textTransform: 'uppercase', color: '#333', marginBottom: 16 }}>Table of Contents</p>
          <ol style={{ columns: 2, columnGap: 40, paddingLeft: 20 }}>
            {sections.map((s, i) => (
              <li key={s.id} style={{ marginBottom: 8 }}>
                <a href={`#${s.id}`} style={{ color: '#b62d83', fontSize: '0.9rem', textDecoration: 'none' }}>
                  {s.title}
                </a>
              </li>
            ))}
          </ol>
        </nav>

        {/* Sections */}
        {sections.map((s, i) => (
          <section key={s.id} id={s.id} style={{ marginBottom: 52, paddingBottom: 52, borderBottom: i < sections.length - 1 ? '1px solid rgba(0,0,0,.07)' : 'none' }}>
            <h2 style={{ fontSize: '1.35rem', fontWeight: 800, color: '#333', marginBottom: 18 }}>
              {s.title}
            </h2>
            {s.content.split('\n\n').map((para, j) => (
              <p key={j} style={{ color: '#555', fontSize: '0.97rem', lineHeight: 1.85, marginBottom: 16 }}>
                {para}
              </p>
            ))}
          </section>
        ))}

        {/* Contact */}
        <section style={{ background: 'var(--navy)', padding: '40px 36px', marginTop: 20 }}>
          <h2 style={{ fontSize: '1.3rem', fontWeight: 800, color: '#fff', marginBottom: 20 }}>Contact Us</h2>
          <p style={{ color: 'rgba(255,255,255,.6)', fontSize: '0.95rem', marginBottom: 16, lineHeight: 1.7 }}>
            If you have any questions about these Terms &amp; Conditions, please contact us:
          </p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            {[
              { label: 'Email', value: 'info@wide-wings.ae', href: 'mailto:info@wide-wings.ae' },
              { label: 'Phone', value: '+971 4 335 2645', href: 'tel:+97143352645' },
              { label: 'Mobile', value: '+971 55 565 7609', href: 'tel:+971555657609' },
              { label: 'Address', value: 'Al Quoz Industrial Area 3, Goshi Warehouse City, Warehouse #47, Dubai, United Arab Emirates', href: null },
            ].map(item => (
              <p key={item.label} style={{ color: 'rgba(255,255,255,.6)', fontSize: '0.92rem', margin: 0 }}>
                <strong style={{ color: '#cfa821' }}>{item.label}:</strong>{' '}
                {item.href
                  ? <a href={item.href} style={{ color: 'rgba(255,255,255,.75)', textDecoration: 'none' }}>{item.value}</a>
                  : item.value
                }
              </p>
            ))}
          </div>
          <div style={{ marginTop: 28 }}>
            <Link href="/contact" className="btn-primary" style={{ display: 'inline-flex' }}>Get in Touch</Link>
          </div>
        </section>
      </div>
    </main>
  );
}
