import Link from 'next/link';
import PrivacyAccordion from './PrivacyAccordion';

export const metadata = {
  title: 'Privacy Policy – Wide Wings Media',
  description: 'Privacy Policy for Wide Wings Media, LLC. Learn how we collect, use, and protect your personal information.',
};

const sections = [
  {
    id: 'who-we-are',
    title: 'Who We Are',
    content: `Wide Wings Media, LLC ("we," "our," or "us") operates the website and application. This Privacy Policy explains how personal information is collected, used, and disclosed when you use our services. By accessing the service, you agree to the collection and use practices described in this policy.`,
  },
  {
    id: 'definitions',
    title: 'Definitions and Key Terms',
    content: `To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, they are strictly defined as:

Cookie: Small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, and remember information about you such as your language preference or login information.

Company: When this policy mentions "Company," "we," "us," or "our," it refers to Wide Wings Media, LLC, located in Dubai, Al Quoz Industrial Area 3, Goshi Warehouse City, Warehouse #47, that is responsible for your information under this Privacy Policy.

Country: Where Wide Wings Media, LLC or the owners/founders of Wide Wings Media, LLC are based — in this case, the United Arab Emirates.

Customer: Refers to the company, organization, or person that signs up to use the Wide Wings Media, LLC Service to manage relationships with consumers or service users.

Device: Any internet-connected device such as a phone, tablet, computer, or any other device that can be used to visit Wide Wings Media, LLC and use the services.

IP Address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.

Personnel: Refers to those individuals who are employed by Wide Wings Media, LLC or are under contract to perform a service on behalf of one of the parties.

Personal Data: Any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.

Service: Refers to the service provided by Wide Wings Media, LLC as described in the relative terms (if available) and on this platform.

Third-party service: Refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.

Website: Wide Wings Media, LLC's site, which can be accessed via this URL: https://wide-wings.ae/

You: A person or entity that is registered with Wide Wings Media, LLC to use the Services.`,
  },
  {
    id: 'what-we-collect',
    title: 'What Information Do We Collect?',
    content: `We collect information from you when you visit our website, register on our site, place an order, subscribe to our newsletter, respond to a survey, or fill out a form.

• Name / Username
• Phone Numbers
• Email Addresses

We may also optionally collect the following from your mobile device:

• Location (GPS) data — used for targeted advertising purposes
• Phonebook / Contacts list — to improve usability of the platform

You are free to choose whether to provide this optional mobile device information. Choosing not to provide it will not affect your ability to use the core services.`,
  },
  {
    id: 'third-party-end-user',
    title: 'Third-Party End User Information',
    content: `Wide Wings Media, LLC collects or obtains personal data about end users from the relevant customer. The customer may voluntarily provide information, including personal data, from their social media platform accounts, in which case Wide Wings Media, LLC may collect that personal data from the relevant social media platform.

You can control the information that you allow Wide Wings Media, LLC to access through the privacy settings on the applicable social media platform.`,
  },
  {
    id: 'third-party-customer',
    title: 'Third-Party Customer Information',
    content: `Wide Wings Media, LLC may receive information about individuals who are prospective customers from third parties. This includes information gathered for fraud prevention and detection purposes when individuals express interest in becoming customers of Wide Wings Media, LLC.

Wide Wings Media, LLC may also collect information about prospective customers from publicly available social media information, subject to your social media account privacy settings.`,
  },
  {
    id: 'sharing',
    title: 'Sharing Information',
    content: `Wide Wings Media, LLC may share the information we collect, including personal information, as follows:

• With advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.

• With our current and future affiliated companies and business partners, and if we are involved in a merger, asset sale, financing, liquidation, bankruptcy, or acquisition of all or some portion of our business to another company.

• With third-party service providers we employ to perform functions on our behalf, such as hosting or operating our website, sending emails, storing files, processing payments, and providing customer service.

• With web analytics companies, application developers, advertising networks, data analytics providers who help us understand how our website is used. These companies may use your IP address and other information for analytics purposes.

• To comply with applicable laws and regulations, to respond to a subpoena, search warrant, or other lawful request for information we receive, or to otherwise protect our rights.`,
  },
  {
    id: 'where-collected',
    title: 'Where and When Is Information Collected?',
    content: `Wide Wings Media, LLC will collect personal information that you submit to us. We may also receive personal information about you from third parties as described in this Privacy Policy.`,
  },
  {
    id: 'how-we-use',
    title: 'How We Use the Information We Collect',
    content: `Any of the information we collect from you may be used in one of the following ways:

• To personalize your experience (your information helps us to better respond to your individual needs)
• To improve our website (we continually strive to improve our website offerings based on the information and feedback we receive from you)
• To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)
• To process transactions
• To administer a contest, promotion, survey, or other site feature
• To send periodic emails`,
  },
  {
    id: 'email-usage',
    title: 'Email Usage',
    content: `By submitting your email address on this website, you agree to receive emails from us. You can cancel your participation in any of these email lists at any time by clicking on the opt-out link or other unsubscribe option that is included in the respective email.

We only send emails to people who have authorized us to contact them, either directly, or through a third party. We do not send unsolicited commercial emails, because we hate spam as much as you do.

By submitting your email address, you also agree to allow us to use your email address for customer audience targeting on platforms like Facebook, where we display custom advertising to specific people who have opted-in to receive communications from us.

If you place an order with us, we will send you emails related to your transaction. If you have provided us your email address and have not opted out, we may send you occasional emails. If you would like to unsubscribe from receiving future emails, you can follow the unsubscribe instructions at the bottom of each email.`,
  },
  {
    id: 'data-retention',
    title: 'Data Retention',
    content: `We will retain your personal information only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your information to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our policies.

If you request deletion of your data and we are required to retain some information for legal or business purposes, we will retain a minimal amount of information and ensure that your personal data is not used for any further processing.`,
  },
  {
    id: 'data-protection',
    title: 'Data Protection',
    content: `Wide Wings Media, LLC is committed to protecting your data. We use industry-standard SSL (Secure Socket Layer) technology to allow the encryption of potentially sensitive information such as your name, address, and other critically sensitive information like your credit card details.

Data transmitted by SSL technology is encrypted to protect information during transfer between your device and our systems. Credit card information is never kept on file after a transaction is complete. However, no method of transmission over the Internet, or method of electronic storage, is 100% secure.

While we use commercially acceptable means to protect your personal information, we cannot guarantee its absolute security. Any transmission of personal information is at your own risk.`,
  },
  {
    id: 'international-transfer',
    title: 'International Transfer',
    content: `Wide Wings Media, LLC is incorporated and operated from the United Arab Emirates. If you are located outside the UAE and choose to provide information to us, please note that we may transfer the information, including personal information, to the UAE and process it there.

We may also transfer your data to affiliated offices, personnel, or third-party providers outside the UAE. Your use of the service followed by your submission of information represents your agreement to this transfer. Wide Wings Media, LLC will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy.`,
  },
  {
    id: 'security',
    title: 'Security',
    content: `The security of your personal information is important to us, and we strive to implement and maintain reasonable, commercially acceptable security procedures and practices appropriate to the nature of the information we store, in order to protect it from unauthorized access, destruction, use, modification, or disclosure.

However, please be aware that no method of transmission over the Internet, or method of electronic storage, is 100% secure. While we strive to use commercially acceptable means to protect your personal information, we cannot guarantee its absolute security.`,
  },
  {
    id: 'update-information',
    title: 'Update Your Information',
    content: `The rights and options to change, update, and exercise control over your personal information depend on your relationship with Wide Wings Media, LLC.

If you are a customer of Wide Wings Media, LLC, you may update, correct, or delete information about you at any time by contacting us. You may also cancel your account. If you wish to cancel your account or request that we no longer use your information, please contact us.

Please note that we may retain certain information as required by law or for legitimate business purposes. We may also retain cached or archived copies of your information for a certain period of time. Incomplete requests will not be processed.

After receiving your request, we will update or delete your personal data from our actively used database as soon as reasonably and technically practicable. Some information may remain in archived or backup records for a limited period.`,
  },
  {
    id: 'personnel',
    title: 'Personnel',
    content: `If you are a Wide Wings Media, LLC worker or applicant, we collect information you voluntarily provide to us. We use the information collected for Human Resources purposes in order to administer benefits to workers and screen applicants.

You may contact us in order to (1) update or correct inaccuracies in your information, (2) change your preferences with respect to communications and other information you receive from us, or (3) receive a record of the information we have relating to you. Such updates, corrections, changes and deletions will have no effect on other information that we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion.`,
  },
  {
    id: 'sale-of-business',
    title: 'Sale of Business',
    content: `We reserve the right to transfer information to a third party in the event of a sale, merger, or other transfer of all or substantially all of the assets of Wide Wings Media, LLC, or any of its Corporate Affiliates (as defined herein), or that portion of Wide Wings Media, LLC or any of its Corporate Affiliates to which the Service relates, or in the event that we discontinue our business or file a petition or have filed against us a petition in bankruptcy, reorganization, or similar proceeding, provided that the third party agrees to adhere to the terms of this Privacy Policy.`,
  },
  {
    id: 'affiliates',
    title: 'Affiliates',
    content: `We may disclose information (including personal information) about you to our Corporate Affiliates. For purposes of this Privacy Policy, "Corporate Affiliate" means any person or entity which directly or indirectly controls, is controlled by or is under common control with Wide Wings Media, LLC, whether by ownership or otherwise. Any information relating to you that we provide to our Corporate Affiliates will be treated by those Corporate Affiliates in accordance with the terms of this Privacy Policy.`,
  },
  {
    id: 'governing-law',
    title: 'Governing Law',
    content: `This Privacy Policy is governed by the laws of the United Arab Emirates without regard to its conflict of laws provision. You consent to the exclusive jurisdiction of the courts in connection with any action or dispute arising between the parties under or in connection with this Privacy Policy except for those individuals who may have rights to make claims under Privacy Shield, or the Swiss-US framework.

The laws of the United Arab Emirates, excluding its conflicts of law rules, shall govern this Agreement and your use of the website. Your use of the website may also be subject to other local, state, national, or international laws.

By using Wide Wings Media, LLC or contacting us directly, you signify your acceptance of this Privacy Policy. If you do not agree to this Privacy Policy, please do not use our website. Continued use of the website following the posting of changes to this policy will be deemed your acceptance of those changes.`,
  },
  {
    id: 'your-consent',
    title: 'Your Consent',
    content: `We've updated our Privacy Policy to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our website, registering an account, or making a purchase, you hereby consent to our Privacy Policy and agree to its terms.`,
  },
  {
    id: 'links',
    title: 'Links to Other Websites',
    content: `This Privacy Policy applies only to the Services. The Services may contain links to other websites not operated or controlled by Wide Wings Media, LLC. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us.

Please remember that when you use a link to go from the Services to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website's own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.`,
  },
  {
    id: 'advertising',
    title: 'Advertising',
    content: `This website may contain third-party advertisements and links to third-party sites. Wide Wings Media, LLC does not make any representation as to the accuracy or suitability of any of the information contained in those advertisements or sites and does not accept any responsibility or liability for the conduct or content of those advertisements and sites and the offerings made by the third parties.

Advertising keeps Wide Wings Media, LLC and many of the websites and services you use free of charge. We work hard to make sure that ads are safe, unobtrusive, and as relevant as possible.`,
  },
  {
    id: 'cookies-advertising',
    title: 'Cookies for Advertising',
    content: `Cookies help to make advertising more effective. Without cookies, it's harder for an advertiser to reach its audience, or to know how many ads were shown and how many clicks they received.

Many websites use advertising cookies to collect data about your online activity and identify your interests, so they can show you advertising that best reflects those interests and avoids repeatedly showing you the same ads.`,
  },
  {
    id: 'cookies',
    title: 'Cookies',
    content: `Wide Wings Media, LLC uses "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our website but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website as we would not be able to remember that you had logged in previously.

Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.`,
  },
  {
    id: 'blocking-cookies',
    title: 'Blocking and Disabling Cookies',
    content: `Wherever you're located you may also set your browser to block cookies and similar technologies, but this action may block our essential cookies and prevent our website from functioning properly, and you may not be able to fully utilize all of its features and services. You should also be aware that you may also lose some saved information (e.g. saved login details, site preferences) if you block cookies on your browser.

Different browsers make different controls available to you. Disabling a cookie or category of cookie does not delete the cookie from your browser, you will need to do this yourself from within your browser. Visit your browser's help menu for more information.`,
  },
  {
    id: 'remarketing',
    title: 'Remarketing Services',
    content: `We use remarketing services. What is remarketing? In digital marketing, remarketing (or retargeting) is the practice of serving ads across the internet to people who have already visited your website. It allows your company to seem like they're "following" people around the internet by serving ads on the websites and platforms they use most.`,
  },
  {
    id: 'payment',
    title: 'Payment Details',
    content: `In respect to any credit card or other payment processing details you have provided us, we commit that this confidential information will be stored in the most secure manner possible.`,
  },
  {
    id: 'kids-privacy',
    title: "Kids' Privacy",
    content: `We collect information from kids under the age of 13 just to better our services. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data without your permission, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.`,
  },
  {
    id: 'policy-changes',
    title: 'Changes to Our Privacy Policy',
    content: `We may change our Service and policies, and we may need to make changes to this Privacy Policy so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to this Privacy Policy and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Privacy Policy. If you do not want to agree to this or any updated Privacy Policy, you can delete your account.`,
  },
  {
    id: 'third-party-services',
    title: 'Third-Party Services',
    content: `We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services ("Third-Party Services").

You acknowledge and agree that Wide Wings Media, LLC shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. Wide Wings Media, LLC does not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.

Third-Party Services and links thereto are provided solely as a convenience to you, and you access and use them entirely at your own risk and subject to such third parties' terms and conditions.`,
  },
  {
    id: 'facebook-pixel',
    title: 'Facebook Pixel',
    content: `Facebook pixel is an analytics tool that allows us to measure the effectiveness of our advertising by understanding the actions people take on our website. You can control how your data is used by Facebook by visiting your Facebook Ad Settings. We use Facebook pixel to show you relevant advertising on Facebook, to measure the results of our advertising campaigns, and to improve our marketing efforts.`,
  },
  {
    id: 'tracking',
    title: 'Tracking Technologies',
    content: `Google Maps API: We use Google Maps API to better serve our users with location-specific features. Google Maps API collects information from you and from your device for security purposes. Google Maps API is governed by Google's Privacy Policy.

Cookies: As noted above, we use cookies to identify areas of our website that you have visited. Cookies are non-essential to basic website use but enhance performance and functionality.

Local Storage: We use Local Storage Objects (LSOs) such as HTML5 to store content and preferences. Third parties with whom we partner to provide certain features on our website or to display advertising based upon your web browsing activity also use HTML5 to collect and store information. Various browsers may offer their own management tools for removing HTML5 LSOs.

Sessions: We use "Sessions" to identify the areas of our website that you have visited. A Session is a small piece of data stored on your computer or mobile device by your web browser.`,
  },
  {
    id: 'gdpr',
    title: 'Information About General Data Protection Regulation (GDPR)',
    content: `What is GDPR?

The EU's General Data Protection Regulation (GDPR) is the world's strongest set of data protection rules, which enhances how people can access information about them and places limits on what organizations can do with personal data. The GDPR applies not just to European organizations but to all companies processing the personal data of people in the EU.

Wide Wings Media, LLC has implemented GDPR controls as a baseline standard for all of our operations worldwide.

What is Personal Data?

Any information that relates to an identified or identifiable living individual. Different pieces of information, which collected together can lead to the identification of a particular person, also constitute personal data. Personal data that has been de-identified, encrypted or pseudonymised but can be used to re-identify a person remains personal data and falls within the scope of the GDPR.

The Data Protection Principles include requirements such as:

• Personal data collected must be processed in a fair, legal, and transparent way and should only be used in a way that a person would reasonably expect.
• Personal data should only be collected to fulfil a specific purpose and it should only be used for that purpose. Organizations must specify why they need the personal data when they collect it.
• Personal data should be held no longer than necessary to fulfil its purpose.
• People covered by the GDPR have the right to access their own personal data. They can also request a copy of their data, and that their data is updated, deleted, restricted, or moved to another organization.

Why is GDPR Important?

GDPR adds some key requirements for organizations that collect data about EU residents. It also increases the stakes for compliance by adding tough new penalties for breach. Wide Wings Media, LLC believes in the importance of protecting data privacy, and we already have solid security and privacy practices in place that go beyond the requirements of this new regulation.

Individual Data Subject's Rights — Data Access, Portability and Deletion

We are committed to helping our customers meet the data subject rights requirements of GDPR. Wide Wings Media, LLC processes or stores all personal data in fully vetted, DPA-compliant vendors. We do store all conversation and personal data for up to 6 years unless you request that we delete it. We give our customers the ability to provide their EU customers with the ability to access, update, retrieve and remove personal data. Wide Wings Media, LLC has the ability to respond to these requests within a reasonable timeframe.`,
  },
  {
    id: 'california',
    title: 'California Residents',
    content: `The California Consumer Privacy Act (CCPA) requires us to disclose categories of Personal Information we collect and how we use it, the categories of sources from whom we collect Personal Information, and the third parties with whom we share it, which we have explained above.

California residents have certain rights with respect to the personal information we have collected about them. These include:

Right to Know and Access: You may submit a verifiable request for information regarding the: (1) categories of Personal Information we collect, use, or share; (2) purposes for which categories of Personal Information are collected or used by us; (3) categories of sources from which we collect Personal Information; and (4) specific pieces of Personal Information we have collected about you.

Right to Equal Service: We will not discriminate against you if you exercise your privacy rights.

Right to Delete: You may submit a verifiable request to close your account and we will delete Personal Information about you that we have collected.

Request that a business that sells a consumer's personal data, not sell the consumer's personal data.

If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.

Wide Wings Media, LLC does not sell the personal information of our users.`,
  },
  {
    id: 'caloppa',
    title: 'California Online Privacy Protection Act (CalOPPA)',
    content: `CalOPPA requires us to disclose categories of Personal Information we collect and how we use it, the categories of sources from whom we collect Personal Information, and the third parties with whom we share it, which we have explained above.

CalOPPA users have the following rights:

Right to Know and Access: You may submit a verifiable request for information regarding the: (1) categories of Personal Information we collect, use, or share; (2) purposes for which categories of Personal Information are collected or used by us; (3) categories of sources from which we collect Personal Information; and (4) specific pieces of Personal Information we have collected about you.

Right to Equal Service: We will not discriminate against you if you exercise your privacy rights.

Right to Delete: You may submit a verifiable request to close your account and we will delete Personal Information about you that we have collected.

Request that a business that sells a consumer's personal data, not sell the consumer's personal data.

If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.

Wide Wings Media, LLC does not sell the personal information of our users.`,
  },
];

export default function PrivacyPolicyPage() {
  return (
    <main style={{ paddingBottom: '80px', background: '#fff' }}>
      {/* Hero */}
      <section style={{ position: 'relative', background: '#0d0d20', padding: '140px 0 80px', overflow: 'hidden' }}>
        <div aria-hidden="true" style={{ position: 'absolute', inset: 0, background: 'radial-gradient(ellipse 60% 60% at 30% 50%, rgba(167,49,132,0.18) 0%, transparent 70%)', pointerEvents: 'none' }} />
        <div className="container" style={{ position: 'relative', zIndex: 1, textAlign: 'center', display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
          <nav style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, fontFamily: 'Calibri, sans-serif', fontSize: '0.88rem', color: 'rgba(255,255,255,0.45)', marginBottom: 20 }} aria-label="breadcrumb">
            <Link href="/" style={{ color: 'rgba(255,255,255,0.45)', textDecoration: 'none' }}>Home</Link>
            <span style={{ color: 'rgba(255,255,255,0.25)' }}>/</span>
            <span>Privacy Policy</span>
          </nav>
          <p style={{ fontFamily: 'Nexa, sans-serif', fontSize: '0.78rem', fontWeight: 800, letterSpacing: '0.14em', textTransform: 'uppercase', color: '#a73184', margin: '0 0 12px' }}>Legal</p>
          <h1 style={{ fontFamily: 'Nexa, sans-serif', fontSize: 'clamp(2.4rem, 5vw, 4rem)', fontWeight: 800, color: '#fff', margin: '0 0 20px', lineHeight: 1.12 }}>
            Privacy Policy
          </h1>
          <p style={{ fontFamily: 'Calibri, sans-serif', fontSize: 'clamp(1rem, 1.8vw, 1.12rem)', color: 'rgba(255,255,255,0.6)', maxWidth: 620, lineHeight: 1.75, margin: 0 }}>
            This Privacy Policy describes how Wide Wings Media, LLC collects, uses, and shares information about you when you use our services.
          </p>
        </div>
      </section>

      {/* Last Updated banner */}
      <div style={{ background: '#111827', borderBottom: '1px solid rgba(255,255,255,0.06)', padding: '14px 0' }}>
        <div className="container" style={{ display: 'flex', alignItems: 'center', gap: 16, flexWrap: 'wrap' }}>
          <span style={{ fontFamily: 'Nexa, sans-serif', fontSize: '0.68rem', fontWeight: 800, letterSpacing: '0.12em', textTransform: 'uppercase', color: '#0d0d20', background: '#cfa821', padding: '4px 10px', borderRadius: 4, whiteSpace: 'nowrap' }}>
            Last Updated
          </span>
          <p style={{ fontFamily: 'Calibri, sans-serif', fontSize: '0.92rem', color: 'rgba(255,255,255,0.75)', margin: 0, flex: 1 }}>
            <strong style={{ fontFamily: 'Nexa, sans-serif', color: '#fff', fontWeight: 700 }}>January 1, 2026</strong>
            {' '}— This policy may be updated periodically. Continued use of our services constitutes acceptance of any changes.
          </p>
        </div>
      </div>

      {/* Content */}
      <div className="container" style={{ maxWidth: 1200, paddingTop: 60 }}>

        {/* Table of Contents */}
        <nav style={{ background: '#f8f9fc', border: '1px solid #ebebeb', borderRadius: 16, padding: '32px 36px', marginBottom: 52 }}>
          <h2 style={{ fontFamily: 'Nexa, sans-serif', fontSize: '1.2rem', fontWeight: 800, color: '#1a1a2e', marginBottom: 24 }}>Table of Contents</h2>
          <ul style={{ columns: 3, columnGap: 32, paddingLeft: 0, margin: 0, listStyle: 'none' }}>
            {sections.map(s => (
              <li key={s.id} style={{ marginBottom: 10, breakInside: 'avoid' }}>
                <a href={`#${s.id}`} style={{ fontFamily: 'Calibri, sans-serif', fontSize: '0.95rem', color: '#4a5568', textDecoration: 'none', lineHeight: 1.5 }}>
                  {s.title}
                </a>
              </li>
            ))}
          </ul>
        </nav>

        {/* First 3 sections — shown normally */}
        {sections.slice(0, 3).map((s, i) => (
          <section
            key={s.id}
            id={s.id}
            style={{ marginBottom: 28, paddingBottom: 28, borderBottom: '1px solid #ebebeb' }}
          >
            <h2 style={{ fontFamily: 'Nexa, sans-serif', fontSize: '1.2rem', fontWeight: 800, color: '#1a1a2e', marginBottom: 16 }}>
              {s.title}
            </h2>
            {s.content.split('\n\n').map((para, j) => (
              <p key={j} style={{ fontFamily: 'Calibri, sans-serif', fontSize: '1rem', color: '#555', lineHeight: 1.85, marginBottom: 14, whiteSpace: 'pre-line' }}>
                {para}
              </p>
            ))}
          </section>
        ))}

        {/* Toggle accordion — from "Third-Party End User Information" onwards */}
        <p style={{ fontFamily: 'Nexa, sans-serif', fontSize: '0.72rem', fontWeight: 800, letterSpacing: '0.12em', textTransform: 'uppercase', color: '#a73184', marginBottom: 4 }}>
          Detailed Policies
        </p>
        <h2 style={{ fontFamily: 'Nexa, sans-serif', fontSize: '1.2rem', fontWeight: 800, color: '#1a1a2e', marginBottom: 0 }}>
          Additional Privacy Information
        </h2>
        <PrivacyAccordion sections={sections.slice(3)} />

        {/* Contact */}
        <section style={{ background: '#0d0d20', borderRadius: 16, padding: '40px 36px', marginTop: 56 }}>
          <h2 style={{ fontFamily: 'Nexa, sans-serif', fontSize: '1.3rem', fontWeight: 800, color: '#fff', marginBottom: 16 }}>Contact Us</h2>
          <p style={{ fontFamily: 'Calibri, sans-serif', color: 'rgba(255,255,255,.6)', fontSize: '1rem', marginBottom: 20, lineHeight: 1.7 }}>
            If you have any questions about this Privacy Policy or our data practices, please contact us:
          </p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            {[
              { label: 'Email',   value: 'info@wide-wings.ae',     href: 'mailto:info@wide-wings.ae' },
              { label: 'Phone',   value: '+971 4 335 2645',        href: 'tel:+97143352645' },
              { label: 'Mobile',  value: '+971 55 565 7609',       href: 'tel:+971555657609' },
              { label: 'Address', value: 'Al Quoz Industrial Area 3, Goshi Warehouse City, Warehouse #47, Dubai, United Arab Emirates', href: null },
            ].map(item => (
              <p key={item.label} style={{ fontFamily: 'Calibri, sans-serif', color: 'rgba(255,255,255,.6)', fontSize: '0.95rem', margin: 0 }}>
                <strong style={{ fontFamily: 'Nexa, sans-serif', color: '#cfa821' }}>{item.label}:</strong>{' '}
                {item.href
                  ? <a href={item.href} style={{ color: 'rgba(255,255,255,.75)', textDecoration: 'none' }}>{item.value}</a>
                  : item.value}
              </p>
            ))}
          </div>
          <div style={{ marginTop: 28 }}>
            <Link href="/contact" className="btn-primary" style={{ display: 'inline-flex' }}>
              Get in Touch
            </Link>
          </div>
        </section>
      </div>
    </main>
  );
}
