export const POSTS = [
  { slug: 'ecommerce-website-development-dubai', title: 'Ecommerce Website Development in Dubai for Scalable Growth', excerpt: 'Get high-converting ecommerce website development in Dubai & UAE. Fast, secure, mobile-first online stores designed for sales growth and ROI.', category: 'Web Development', image: '/blog/ecommerce-website-development-dubai.webp' },
  { slug: 'search-engine-marketing-company-dubai', title: 'Search Engine Marketing Company in Dubai — SEM Services UAE', excerpt: 'ROI-focused search engine marketing company in Dubai delivering high-intent PPC campaigns built for UAE buyers. Get a free SEM audit today.', category: 'SEM', image: '/blog/search-engine-marketing-company-dubai.webp' },
  { slug: 'ppc-for-ecommerce-dubai', title: 'PPC for E-commerce Websites in Dubai: Where to Start', excerpt: 'Smart PPC for e-commerce websites in Dubai that aligns with buyer intent — not clicks. Decision-led Google Ads and Shopping campaigns.', category: 'PPC', image: '/blog/ppc-for-ecommerce-dubai.webp' },
  { slug: 'instagram-growth-services-uae', title: 'How to Choose the Best Instagram Growth Services in UAE', excerpt: 'Learn how to choose the best Instagram growth services in UAE. Proven strategies, local insights, and tips to grow followers & sales.', category: 'Social Media', image: '/blog/instagram-growth-services-uae.webp' },
  { slug: 'shopify-web-development-dubai', title: 'Shopify Web Development in Dubai for Ecommerce Growth', excerpt: 'Expert Shopify web development in Dubai focused on speed, Arabic UX, local payments & conversions. Built for real UAE ecommerce growth.', category: 'Web Development', image: '/blog/shopify-web-development-dubai.webp' },
  { slug: 'videography-company-dubai', title: 'Professional Videography & Photography Services in Dubai', excerpt: 'Hire a top videography company in Dubai for cinematic videos, photography, drone shots, events, and corporate productions across the UAE.', category: 'Creative', image: '/blog/videography-company-dubai.webp' },
  { slug: 'b2b-seo-services-in-dubai', title: 'B2B SEO Services in Dubai: Revenue with Strategic Authority', excerpt: 'Boost revenue with expert B2B SEO Services in Dubai. Drive qualified leads, build authority, and win high-intent decision-makers in the UAE.', category: 'SEO', image: '/blog/b2b-seo-services-in-dubai.webp' },
  { slug: 'digital-marketing-for-restaurants', title: 'Digital Marketing in UAE for Restaurant Success', excerpt: 'Digital marketing for restaurants in UAE that drives bookings, boosts visibility, and grows your brand across Dubai and the wider region.', category: 'Digital Marketing', image: '/blog/digital-marketing-for-restaurants.webp' },
  { slug: 'google-ads-agency-dubai', title: 'Google Ads Agency in Dubai: Get Measurable Results Today!', excerpt: 'Wide Wings Media is your leading Google Ads Agency in Dubai for data-driven campaigns, targeted leads, & measurable ROI for business growth.', category: 'PPC', image: '/blog/google-ads-agency-dubai.webp' },
  { slug: 'healthcare-marketing-agency-in-dubai', title: 'How Healthcare Brands Are Winning with Digital Marketing', excerpt: 'Healthcare marketing agency in Dubai that fosters patient growth for clinics and hospitals. Contact us for a free strategy session.', category: 'Healthcare', image: '/blog/healthcare-marketing-agency-in-dubai.webp' },
  { slug: 'reliable-paid-ads-agency-in-dubai', title: 'Paid Ads Agency in Dubai: Boost ROI with Expert Ad Campaigns', excerpt: 'Partner with a reliable paid ads agency in Dubai. Get data-driven Google, Meta & LinkedIn campaigns that grow leads and maximize ROI.', category: 'PPC', image: '/blog/reliable-paid-ads-agency-in-dubai.webp' },
  { slug: 'seo-strategy-for-uae-startups', title: 'Best SEO Strategy for UAE Startups: A Data-Driven Guide', excerpt: 'Discover the best SEO strategy for UAE startups — local SEO, bilingual content, mobile optimization & proven tactics to outrank competitors.', category: 'SEO', image: '/blog/seo-strategy-for-uae-startups.webp' },
  { slug: 'ai-trend', title: 'AI Trends: Driving the Future of Technology in the UAE', excerpt: 'Explore the latest AI trends in the UAE. See how generative AI and automation are boosting business productivity and driving innovation.', category: 'Technology', image: '/blog/ai-trend.webp' },
  { slug: 'real-estate-content-writing-uae', title: 'Real Estate Content Writing Services in UAE: Why They Work', excerpt: 'Boost visibility, leads, and trust with SEO-rich, multilingual, and visual real estate content writing services tailored for the UAE market.', category: 'Content', image: '/blog/real-estate-content-writing-uae.webp' },
  { slug: 'local-seo-services-in-abu-dhabi', title: 'How Local SEO Services in Abu Dhabi Can Boost Your Business', excerpt: 'Improve your local visibility in Abu Dhabi with local SEO services. Rank higher on Google to attract nearby customers and grow your business.', category: 'SEO', image: '/blog/local-seo-services-in-abu-dhabi.webp' },
  { slug: 'social-media-packages-for-smes', title: 'Social Media Packages for SMEs in the UAE: What to Expect', excerpt: 'Explore social media packages for SMEs in the UAE — compare pricing, platforms, ROI tracking, and local engagement strategies.', category: 'Social Media', image: '/blog/social-media-packages-for-smes.webp' },
  { slug: 'digital-marketing-strategies-for-smes', title: 'Digital Marketing in Dubai: 5 Smart Strategies for SMEs', excerpt: 'From local SEO to AI, explore proven digital marketing strategies for SMEs in Dubai. Perfect for growing your brand in a competitive market.', category: 'Digital Marketing', image: '/blog/digital-marketing-strategies-for-smes.webp' },
  { slug: 'local-seo-agency-for-startups', title: 'Top-rated Local SEO Agency in Dubai, UAE', excerpt: 'Boost your visibility with expert local SEO services in the UAE. Attract more customers with the top-rated local SEO agency in Dubai.', category: 'SEO', image: '/blog/local-seo-agency-for-startups.webp' },
  { slug: 'what-is-a-url', title: 'Short vs. Long URLs in SEO: What Actually Works?', excerpt: 'Understand how URL structure impacts SEO in Dubai and the UAE. Learn best practices for short vs. long URLs to improve search rankings.', category: 'SEO', image: '/blog/what-is-a-url.webp' },
  { slug: 'social-media-for-powerful-brand-awareness', title: 'Social Media for Brand Awareness: What Works Best?', excerpt: 'Discover how social media drives powerful brand awareness for businesses in Dubai and the UAE. Strategies that convert followers into customers.', category: 'Social Media', image: '/blog/social-media-for-powerful-brand-awareness.webp' },
  { slug: 'ai-in-healthcare-marketing', title: 'How AI in Healthcare is Transforming the Future of Medicine', excerpt: 'Rapid technological breakthroughs and increasing demand for personalized, accessible services are driving AI in healthcare transformation.', category: 'Healthcare', image: '/blog/ai-in-healthcare-marketing.webp' },
  { slug: 'advertisement-company-in-dubai', title: 'Advertising Company in Dubai: Meet Your Target Market', excerpt: 'Want more people to know about your brand in Dubai? Our premium advertisement company creates effective campaigns for all kinds of clients.', category: 'Advertising', image: '/blog/advertisement-company-in-dubai.webp' },
  { slug: 'broadcast-tv-advertising-for-millions', title: 'Maximize Your Reach: Broadcast TV Advertising to Millions', excerpt: 'Reach the right audience, in the right location, at the right time with broadcast TV advertising services across the UAE.', category: 'Advertising', image: '/blog/broadcast-tv-advertising-for-millions.webp' },
  { slug: 'connected-tv-advertising', title: 'Connected TV Advertising: Reach Millions with Ease', excerpt: 'Level up your marketing! Harness the power of connected TV advertising to broadcast your ads to millions of viewers effortlessly.', category: 'Advertising', image: '/blog/connected-tv-advertising.webp' },
  { slug: 'impact-of-ai-on-marketing-and-advertising', title: 'How Will AI Affect Marketing and Advertising?', excerpt: 'Use AI to improve your marketing! Learn the power of AI for marketing and advertising to make strategies better and more personalized.', category: 'Technology', image: '/blog/impact-of-ai-on-marketing-and-advertising.webp' },
  { slug: 'creative-street-marketing-solutions', title: 'Make an Impact With Smart Street Marketing & Advertisements', excerpt: 'Creative street marketing solutions in Dubai that drive brand awareness and foot traffic. Outdoor campaigns built for real impact.', category: 'OOH', image: '/blog/creative-street-marketing-solutions.webp' },
  { slug: 'structured-data-for-enhanced-seo-performance', title: 'Structured Data for Enhanced SEO Performance', excerpt: 'Structured data is a format designed to be easily understood by computers. Learn how it improves your search engine performance in the UAE.', category: 'SEO', image: '/blog/structured-data-for-enhanced-seo-performance.webp' },
  { slug: 'systematic-search-engine-optimization', title: 'SEO Services in Dubai: How to Get Your Business Noticed', excerpt: 'Systematic search engine optimization services in Dubai. Get your business noticed online with proven SEO tactics and strategies.', category: 'SEO', image: '/blog/systematic-search-engine-optimization.webp' },
  { slug: 'brand-lift-tests', title: 'Brand Lift Tests: A Complete Guide for Digital Marketers', excerpt: 'Brand lift tests measure real impact of your campaigns. A complete guide for digital marketers in Dubai and the wider UAE market.', category: 'Analytics', image: '/blog/brand-lift-tests.webp' },
  { slug: 'marketing-for-ecommerce-businesses', title: 'Marketing for Ecommerce Businesses', excerpt: 'Explore effective digital marketing strategies for e-commerce businesses. Learn about SEO, social media, email marketing, and PPC to grow.', category: 'Ecommerce', image: '/blog/marketing-for-ecommerce-businesses.webp' },
  { slug: 'content-repurposing', title: 'Improve Your Impact by Using Content Repurposing', excerpt: 'Unlock the hidden value of content repurposing. Learn how to extend the life of your content and reach more audiences with less effort.', category: 'Content', image: '/blog/content-repurposing.webp' },
  { slug: 'local-seo-and-ai-for-small-businesses', title: 'We Help Local Businesses Grow Through Local SEO and AI', excerpt: 'Help local businesses grow by leveraging location-based search strategies and artificial intelligence technology in Dubai and the UAE.', category: 'SEO', image: '/blog/local-seo-and-ai-for-small-businesses.webp' },
  { slug: 'social-media-for-small-businesses', title: "Social Media for Small Businesses: It's Not All Easy", excerpt: 'Are you thinking about using social media marketing for your small business? Read this blog to learn about your challenges and how to overcome them.', category: 'Social Media', image: '/blog/social-media-for-small-businesses.webp' },
  { slug: 'what-are-open-graph-tags', title: 'Open Graph Tags: Want to Use Social Media More Effectively?', excerpt: 'Learn how Open Graph Tags can help you get more clicks, shares, and engagement for your content across social platforms.', category: 'SEO', image: '/blog/what-are-open-graph-tags.webp' },
  { slug: 'what-are-anchor-texts', title: 'What Are Anchor Texts? Why Are They Important for SEO?', excerpt: 'Anchor texts are a key SEO element. Learn what they are, why they matter, and how to use them effectively in your content strategy.', category: 'SEO', image: '/blog/what-are-anchor-texts.webp' },
  { slug: 'digital-marketing-strategy-for-b2bs', title: 'A Marketing Strategy for B2B Companies', excerpt: 'Discover a winning digital marketing strategy for B2B companies in Dubai. Drive qualified leads and grow revenue with targeted campaigns.', category: 'B2B', image: '/blog/digital-marketing-strategy-for-b2bs.webp' },
  { slug: 'image-optimization-tips', title: 'Boost Website Traffic: Image Optimization Guide for Bloggers', excerpt: "Increase visitors to your website with our blogger's guide to image optimization for improving user experience and search traffic.", category: 'SEO', image: '/blog/image-optimization-tips.webp' },
  { slug: 'best-digital-marketing-agency-in-abu-dhabi', title: 'Digital Marketing Agency in Abu Dhabi for Growth', excerpt: 'Use digital tools to make your business grow! Wide Wings is a digital marketing agency in Abu Dhabi that helps companies grow locally and regionally.', category: 'Digital Marketing', image: '/blog/best-digital-marketing-agency-in-abu-dhabi.webp' },
  { slug: 'top-social-media-marketing-agencies-in-dubai', title: 'List of the Top 10 Social Media Marketing Agencies in Dubai', excerpt: 'Improve your social media presence! Explore the top 10 social media marketing agencies in Dubai to help your business grow.', category: 'Social Media', image: '/blog/top-social-media-marketing-agencies-in-dubai.webp' },
  { slug: 'healthcare-marketing', title: 'Healthcare Marketing Agency Driven By AI Technology', excerpt: 'A healthcare marketing agency that uses AI technology to drive patient growth for clinics, hospitals, and healthcare brands across the UAE.', category: 'Healthcare', image: '/blog/healthcare-marketing.webp' },
  { slug: 'what-are-banner-ads', title: 'Make the Most of Banner Ads! Tips and Targeting Strategies', excerpt: 'Use banner ads to get more customers! This guide teaches you everything from design tips to targeting strategies for your campaigns.', category: 'Advertising', image: '/blog/what-are-banner-ads.webp' },
  { slug: 'power-of-bridge-banner-advertising', title: 'Bridge Banner Ads: A Cost-Effective Solution for Your Business', excerpt: 'Unlock your business potential with bridge banner advertising. Cost-effective, high-visibility OOH advertising across Dubai and the UAE.', category: 'OOH', image: '/blog/power-of-bridge-banner-advertising.webp' },
  { slug: 'power-of-shopping-mall-advertising', title: 'Shopping Mall Advertising as the New Marketing Frontier', excerpt: 'Learn how shopping mall advertising reaches modern consumers. Discover strategies to market products in physical retail spaces.', category: 'OOH', image: '/blog/power-of-shopping-mall-advertising.webp' },
  { slug: 'market-segmentation-and-targeting', title: 'Market Segmentation: Targeting the Right Customers', excerpt: 'Learn the essentials of market segmentation and targeting. Discover how to divide markets and reach the right customers effectively.', category: 'Strategy', image: '/blog/market-segmentation-and-targeting.webp' },
  { slug: 'power-of-reputation-management', title: 'A Guide to Reputation Management: Manage Your Reputation', excerpt: 'How do people see your company online? Learn the latest strategies for reputation management in the digital age and improve your brand presence.', category: 'PR', image: '/blog/power-of-reputation-management.webp' },
  { slug: 'premier-cinema-advertising-company', title: 'Cinema Advertising: Connect with Emotion', excerpt: 'Cinema advertising creates emotional connections with audiences. Reach captivated viewers in a premium environment across UAE cinemas.', category: 'Advertising', image: '/blog/premier-cinema-advertising-company.webp' },
  { slug: 'best-time-to-post-on-instagram-in-uae', title: 'Learn the Best Times to Post on Instagram in the UAE', excerpt: 'Find out the best times to post on Instagram in the UAE, including weekdays and weekends, to maximize engagement and reach your audience.', category: 'Social Media', image: '/blog/best-time-to-post-on-instagram-in-uae.webp' },
  { slug: 'guide-to-effective-social-media-campaign', title: 'Guide to a Successful Social Media Campaign', excerpt: 'Want to learn how to create and manage a successful social media campaign? Our simple guide teaches you how to connect and engage people effectively.', category: 'Social Media', image: '/blog/guide-to-effective-social-media-campaign.webp' },
  { slug: 'youtube-studio-for-more-views', title: 'How to Use YouTube Studio Tools to Grow Your Channel', excerpt: "Unlock your channel's potential with essential YouTube Studio strategies for optimizing views and engaging your audience effectively.", category: 'Content', image: '/blog/youtube-studio-for-more-views.webp' },
  { slug: 'ai-video-creation-trends', title: 'AI Video Creation Trends and Their Industry Impact', excerpt: "Learn about the latest trends in AI video creation, how they're impacting the industry, and experts' predictions for the future.", category: 'Technology', image: '/blog/ai-video-creation-trends.webp' },
  { slug: 'successfully-rebrand-your-business', title: 'How to Develop Your Rebranding Strategy', excerpt: 'Want to know how to rebrand your business successfully? Learn the key steps to developing a rebranding strategy that resonates with your audience.', category: 'Branding', image: '/blog/successfully-rebrand-your-business.webp' },
  { slug: 'how-to-keep-your-audience-engaged', title: 'Boost Audience Engagement in a Distracted World', excerpt: 'Learn proven strategies for capturing and sustaining audience engagement in a distracted world. Boost attention and interaction effectively.', category: 'Content', image: '/blog/how-to-keep-your-audience-engaged.webp' },
  {
    slug: 'ppc-advertising-company-dubai',
    title: 'PPC Advertising Company in Dubai',
    excerpt: 'Explore our expert insights on ppc advertising company in dubai.',
    category: 'Insights',
    image: '/images/blog/default.jpg',
    date: '2026-06-25',
    readTime: '8 min read',
  },
  {
    slug: 'social-media-marketing-agency-in-dubai',
    title: 'Social Media Marketing',
    excerpt: 'Explore expert insights: Social Media Marketing.',
    category: 'Insights',
    image: '/images/blog/default.jpg',
    date: '2026-06-25',
    readTime: '8 min read',
  },
  {
    slug: 'content-creation-graphic-design',
    title: 'Wide Wings Media | Leading Digital Marketing Agency in Dubai',
    excerpt: 'Wide Wings Media | Leading Digital Marketing Agency in Dubai.',
    category: 'Insights',
    image: '/images/blog/default.jpg',
    date: '2026-06-25',
    readTime: '8 min read',
  },
  {
    slug: 'email-sms-crm-marketing',
    title: 'Wide Wings Media | Leading Digital Marketing Agency in Dubai',
    excerpt: 'Wide Wings Media | Leading Digital Marketing Agency in Dubai.',
    category: 'Insights',
    image: '/images/blog/default.jpg',
    date: '2026-06-25',
    readTime: '8 min read',
  },
  {
    slug: 'outdoor-advertising-dubai',
    title: 'Outdoor Advertising',
    excerpt: 'Outdoor Advertising.',
    category: 'Insights',
    image: '/images/blog/default.jpg',
    date: '2026-06-25',
    readTime: '8 min read',
  },
  {
    slug: 'analytics-performance-marketing',
    title: 'Analytics & Performance Marketing',
    excerpt: 'Analytics & Performance Marketing.',
    category: 'Insights',
    image: '/images/blog/default.jpg',
    date: '2026-06-25',
    readTime: '8 min read',
  },
];
